### PR TITLE
feat(builder): add linux and macos builder

### PR DESCRIPTION
**Pull request by sbsrnt**
As suggested by one of the users - adding linux builder.

I'm not sure what to expect from `publish: never` but if that may help with AppImage on linux then it sounds good to me. See: https://www.electron.build/configuration/publish

### CODE REVIEW

**Review by petterannerwall — APPROVED** [review]

**Comment by sbsrnt** [comment]
@Rai4n yeah I discovered yesterday while fixing dev authorization that we actually don't support linux and macos protocol handling

**Comment by Rai4n** [comment]
> I just merged the protocol handling locally so maybe it could work in your case - let me know about it

When you say locally, are you refering to a branch or this PR. Because I find it hard to find the changes in this repo for handling the protocol on linux. If you have the changes only on a local branch, give them a push to this PR or a remote branch, and I will check them out.

**Comment by Rai4n** [comment]
The latest commit to this PR merged with "fix/protocol-on-dev", seems to work if you added `process.platform == "linux"`.

See the added code
https://github.com/Rai4n/exilence-next/commit/a65dd77b6df05ab24d309174eb172b743d6f7bdc#diff-3f2d9e86dc13f9ee569f58fd0c05aa52fd81460a942027ca4bf54d8d55d07f6d

**Comment by elmo667** [comment]
@Rai4n could you lay out the manual steps you took there? I understand adding a .desktop to .local/share/applications to "register" an app for the mimetype, but whats the second step. Somehow add it to mimeinfo.cache?

**Comment by Rai4n** [comment]
I will probably create a "exilence-next" folder in the .local/share/, then move the released AppImage into that folder. But your .desktop is completely fine.

**Pull request merged**
