### PR TITLE
Add cumulative value / rolling sum in table view

### PR DESCRIPTION
**Pull request by maximumstock**
Let me start by saying that I like your project! I thought about contributing and just picked something that I felt I can help with. 

I tried to implement the requested feature in https://github.com/viktorgullmark/exilence-next/issues/523. 
If this is not relevant anymore, feel free to close my PR.

At first, I added an additional column to render the cumulative value, but it felt too wasteful in terms of table space and felt like cluttering in an unnecessary column. Plus, this would create the problem that you don't really want to order by the cumulative value, which would then require additional logic to disable ordering on certain columns.

So I stuck with simply formatting the `Total value` column in a different way. `ItemTable` already had all the data and now calculates and shows cumulative item value.

### CODE REVIEW

**Comment by viktorgullmark** [comment]
Thanks for your contribution! We havent been very active in maintaining the project, but I will take a look asap to see if we can merge it for the next release :) Expect a review shortly!

**Comment by viktorgullmark** [comment]
We will implement this when we have added support for showing/hiding columns. I feel it should be its own column but its too niche to take up space right now. I will leave this PR open and merge once weve added said functionality!

**Comment by maximumstock** [comment]
Sure, tbh the way I implemented this felt a bit too hacky anyway. Adding support for showing/hiding columns seems very reasonable 👍 .

**Comment by viktorgullmark** [comment]
I broke this PR abit with the reworks to item table. Not entirely sure what the best way would be to get the cumulative value in here.. @maximumstock @sbsrnt

**Comment by viktorgullmark** [comment]
Closing due to inactvity and the fact that this has to be sort of rewritten after the table rewrite.

**Pull request closed without merging**
